config/routes.rb
RedmineApp::Application.routes.draw do

  resources :toggl_entries do
    collection do
      get :all_entries
      get 'filter_by_user/:filter_user_id', :action => :filter_by_user, :as => :filter_by_user
    end
  end

end

app/models/toggl_entry.rb
class TogglEntry < ActiveRecord::Base

  ISSUE_MATCHER = /\s*#(\d+)\s*/
  DEFAULT_COLOR = '#000000'.freeze
  EMAIL_VALIDATOR = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  TOGGL_TAG_SEPARATOR = ','.freeze
  TOGGL_MULTI_TAG_SEPARATOR = '|'.freeze


  serialize :toggl_tags, JSON

  belongs_to :user
  belongs_to :issue
  belongs_to :time_entry

  belongs_to :toggl_workspace
  belongs_to :toggl_project
  belongs_to :toggl_task

  scope :without_issue, -> {where(:issue_id => nil)}
  scope :without_project, -> {where(:pid => nil)}
  scope :for_user, -> (user) {where(:user_id => user)}
  scope :for_issue, -> (issue) {where(:issue_id => issue)}
  scope :order_by_start, -> {order(:start)}
  scope :order_by_user, -> {joins(:user).order('users.firstname, users.lastname')}
  scope :started_after, -> (timeval) {where('start > ?', timeval) if timeval}
  scope :stopped_before, -> (timeval) {where('stop <= ?', timeval) if timeval}
  scope :missing_issue, -> {without_issue.order_by_start.order_by_user}
  scope :missing_project, -> {without_project.order_by_start.order_by_user}

  validates_presence_of :user_id, :toggl_id


  def self.report_without_issue(started_after = nil, stopped_before = nil)
    missing_issue.started_after(started_after).stopped_before(stopped_before).group_by{|k| k.user.name}
  end

  def self.report_without_issue_for_user(user, started_after = nil, stopped_before = nil)
    for_user(user).missing_issue.started_after(started_after).stopped_before(stopped_before).group_by{|k| k.user.name}
  end

  def self.report_without_project(started_after = nil, stopped_before = nil)
    includes(:user, :toggl_workspace).missing_project.started_after(started_after).stopped_before(stopped_before).
      reject{|k| k.user.try(:toggl_workspace)}.
      group_by{|k| k.user.name}
  end

  def self.report_without_project_for_user(user, started_after = nil, stopped_before = nil)
    for_user(user).missing_project.started_after(started_after).stopped_before(stopped_before).group_by{|k| k.user.name}
  end

  def self.export_to_csv(args)
    start_date = args[:start_date]
    end_date = args[:end_date]
    data = eager_load(:toggl_project, :issue).includes(:toggl_task, :user).
      started_after(start_date).stopped_before(end_date).order_by_start

    raw_csv = CSV.generate :force_quotes => true do |csv|
      data.each do |toggl_entry|
        csv << [
          toggl_entry.description,
          toggl_entry.toggl_project_name,
          toggl_entry.formatted_issue,
          toggl_entry.formatted_duration,
          format_time(toggl_entry.start),
          toggl_entry.clean_toggl_tags.join(','),
          toggl_entry.user.try(:name)
        ]
      end
    end

    raw_csv
  end

  def clean_toggl_tags
    return [] if toggl_tags.blank?

    toggl_tags
  end

  def formatted_duration
    Time.at(duration || 0).utc.strftime('%H:%M:%S')
  end

  def formatted_issue
    return nil unless issue

    "#{issue.tracker} ##{issue.id}: #{issue.subject}"
  end

  def toggl_project_color
    toggl_project.try(:hex_color) || DEFAULT_COLOR
  end

  def toggl_workspace_name
    toggl_workspace.try(:name)
  end

  def toggl_project_name
    toggl_project.try(:name)
  end

  def toggl_task_name
    toggl_task.try(:name)
  end

  def toggl_params
    duration ||= (stop - start).ceil

    opts = {
      'description' => description,
      'start' => start.try(:iso8601),
      'duration' => duration
    }

    opts['workspace_id'] = toggl_workspace.try(:toggl_id)
    opts['project_id'] = toggl_project.try(:toggl_id)
    opts['task_id'] = toggl_task.try(:toggl_id)
    opts['tags'] = clean_toggl_tags
    opts['stop'] = stop.try(:iso8601) if stop

    opts
  end

  def detect_issue
    if description.blank?
      self.issue_id = nil
      return
    end

    self.issue_id = description.scan(ISSUE_MATCHER).first.try(:last).try(:to_i)
    return unless self.issue_id

    unless self.issue&.visible?(self.user)
      Rails.logger.info "Toggl ERROR user #{self.user&.login} do not have access to issue #{self.issue_id}"
      raise I18n.t('toggl.user_is_not_authorized_for_issue', :issue => self.issue_id, :user => self.user&.login)
    end
  end

  def delete_time_entry
    return unless issue_id_changed?

    self.time_entry.destroy if self.time_entry
    self.time_entry_id = nil
  end

  def update_time_entry
    self.issue = Issue.find_by_id(issue_id)

    # toggl sends us times in UTC, normal tz conversion happens properly but for time_entry
    # the day and hour components are parsed regardless of the timezone, so we force
    # user timezone
    tz = self.user.time_zone.presence
    start_in_user_timezone = tz ? start.in_time_zone(tz) : start

    if self.issue &&
      (self.user.allowed_to?(:log_time, self.issue.project) ||
       self.user.toggl_can_log_time_to_all_issues)

      time_entry_attributes = {
        :project_id => self.issue.project.id,
        :issue_id => self.issue.id,
        :user => self.user,
        :hours => duration.to_f / 3600,
        :spent_on => start_in_user_timezone,
        :comments => description.gsub(ISSUE_MATCHER, ' ').strip
      }

      related_activity = RedmineToggl.activity_for_tags(clean_toggl_tags) || TimeEntryActivity.default.try(:id)
      time_entry_attributes[:activity_id] = related_activity if related_activity.present?

      self.time_entry ||= build_time_entry
      self.time_entry.assign_attributes(time_entry_attributes)
      self.time_entry.save! if self.time_entry.changed?
    else
      # we only create time_entries for issues, so if no issue, no time_entry
      self.time_entry.destroy if self.time_entry
      self.time_entry_id = nil
      self.issue_id = nil
    end
  end

  def save_if_changed
    detect_issue
    return unless changed?

    transaction do
      delete_time_entry
      update_time_entry
      save!
    end

    self
  end

  def sync_and_destroy
    transaction do
      toggl = TogglService.new(:user => user)
      toggl.delete_time_entry(toggl_id, wid)
      time_entry.destroy if time_entry
      destroy
    end
  end
end

app/controllers/toggl_entries_controller.rb
class TogglEntriesController < ApplicationController

  before_action :set_toggl_entry, :only => [:show, :edit, :update, :destroy]
  before_action :authorize_global
  before_action :user_can_create_toggl_entry, :only => [:new, :create]
  before_action :user_can_view_others_entries, :only => [:all_entries, :filter_by_user]
  before_action :set_user, :only => [:index, :all_entries, :filter_by_user]
  before_action :parse_toggl_tags, :only => [:create, :update]

  helper_method :user_can_create_toggl_entry, :user_can_edit_toggl_entry, :user_can_edit_all_toggl_entries,
    :user_can_view_others_entries


  def index
    respond_to do |format|
      format.html
      format.json {
        render :json => TogglEntriesDatatable.new(TogglEntry, view_context, @user.id)
      }
    end
  end

  def all_entries
    respond_to do |format|
      format.html
      format.json {
        render :json => TogglEntriesDatatable.new(TogglEntry, view_context)
      }
    end
  end

  def filter_by_user
    @filter_user = User.find(params[:filter_user_id])

    respond_to do |format|
      format.html
      format.json {
        render :json => TogglEntriesDatatable.new(TogglEntry, view_context, @filter_user.id)
      }
    end
  end

  def show
    raise Unauthorized unless user_can_view_toggl_entry(@toggl_entry)
  end

  def new
    @toggl_entry = TogglEntry.new
    @toggl_entry.description = "##{params[:issue_id]} " if params[:issue_id]
  end

  def create
    toggl = TogglService.new(:user => User.current)
    @toggl_entry = toggl.create_time_entry(toggl_entry_params)

    if params[:continue]
      redirect_to new_toggl_entry_path, :notice => t('toggl.toggl_entry_created')
    else
      redirect_to @toggl_entry, :notice => t('toggl.toggl_entry_created')
    end
  rescue => e
    Rails.logger.error "Toggl ERROR: #{e.message}\n#{e.backtrace}"
    flash.now[:error] = e.message
    @toggl_entry = TogglEntry.new
    render :new
  end

  def edit
    raise Unauthorized unless user_can_edit_toggl_entry(@toggl_entry)
  end

  def update
    raise Unauthorized unless user_can_edit_toggl_entry(@toggl_entry)

    toggl = TogglService.new(:user => @toggl_entry.user)
    toggl.update_time_entry(toggl_entry_params, @toggl_entry)
    redirect_to @toggl_entry, :notice => t('toggl.toggl_entry_updated')
  rescue => e
    Rails.logger.error "Toggl ERROR: #{e.message}\n#{e.backtrace}"
    flash.now[:error] = e.message
    render :edit
  end

  def destroy
    raise Unauthorized unless user_can_edit_toggl_entry(@toggl_entry)

    @toggl_entry.sync_and_destroy
    redirect_to toggl_entries_url, :notice => t('toggl.toggl_entry_deleted')
  rescue => e
    Rails.logger.error e
    flash[:error] = e.message
    redirect_to toggl_entries_url, :notice => e.message
  end


  private


  def set_user
    @user = User.current
  end

  def set_toggl_entry
    @toggl_entry = TogglEntry.find(params[:id])
  end

  def parse_toggl_tags
    params[:toggl_entry][:toggl_tags] = params[:toggl_entry][:toggl_tags].split(TogglEntry::TOGGL_TAG_SEPARATOR)
  end

  def toggl_entry_params
    params.require(:toggl_entry).permit(
      :description, :start, :stop, :duration, :toggl_id, :user_id,
      :toggl_workspace_id, :toggl_project_id, :toggl_task_id, :toggl_tags => []
    )
  end

  def user_can_create_toggl_entry
    User.current.toggl_can_create_toggl_entry
  end

  def user_can_edit_all_toggl_entries
    User.current.allowed_to_globally?(:edit_all_toggl_entries)
  end

  def user_can_edit_toggl_entry(toggl_entry)
    return true if user_can_edit_all_toggl_entries
    user_can_edit_own_entries(toggl_entry)
  end

  def user_can_view_toggl_entry(toggl_entry)
    return true if user_can_view_others_entries
    toggl_entry.user.id == User.current.id
  end

  def user_can_view_others_entries
    User.current.toggl_can_view_others_entries
  end

  def user_can_edit_own_entries(toggl_entry)
    usr = User.current
    time_entry = toggl_entry.time_entry
    user_owns_entry = toggl_entry.user.id == usr.id
    # if no time_entry then there is no issue, so we do not know which project this is for
    return user_owns_entry unless time_entry

    project = time_entry.project
    # allow if the user can edit all time_entries in the project
    return true if usr.allowed_to?(:edit_time_entries, project)

    # if user can not edit others entries, and does not own the entry, they can not edit it
    return false unless user_owns_entry

    # user owns the entry, see if they can edit their own entry
    return usr.allowed_to?(:edit_own_time_entries, project)
  end
end

app/helpers/toggl_entries_helper.rb
module TogglEntriesHelper

  def rt_issue_link(issue)
    return '' unless issue

    if issue.visible?(User.current)
      link_to_issue(issue)
    else
      "##{issue.id}"
    end
  end

  def rt_time_entry_link(time_entry)
    return '' unless time_entry

    if time_entry.editable_by?(User.current)
      link_to("##{time_entry.id}", edit_time_entry_path(time_entry))
    else
      "##{time_entry.id}"
    end
  end

  def rt_user_link(user)
    return '' if user.blank?
    return h(user.to_s) unless user.is_a?(User)

    name = h(user.name)
    return name unless user.active? || (User.current.admin? && user.logged?)

    link_to name, filter_by_user_toggl_entries_path(:filter_user_id => user.id), :class => user.css_classes
  end

  def rt_format_duration(total_seconds)
    Time.at(total_seconds || 0).utc.strftime('%H:%M:%S')
  end

  def rt_project_display(toggl_entry)
    return '' unless toggl_entry.toggl_project

    color = toggl_entry.toggl_project_color
    style = color.present? ? "style='color:#{color};'" : ''

    "<span title='#{toggl_entry.toggl_task_name}' #{style}>#{toggl_entry.toggl_project_name}</span>"
  end

  def rt_user_timezone_with_fallback
    tz = User.current.time_zone
    return tz if tz.present?

    ActiveSupport::TimeZone[Time.now.zone.to_i]
  rescue
    'UTC'
  end
end

app/views/toggl_entries/_form.html.erb
<%= f.hidden_field :toggl_id %>

<div class="box tabular">
  <div>
    <p>
      <label><%= l('toggl.description') %></label>
      <%= f.text_field :description, :size => 80, :label => '' %>
    </p>

    <% Time.use_zone(rt_user_timezone_with_fallback)  do %>
      <p>
        <label><%= l('toggl.start') %></label>
        <%= f.datetime_select :start %>
      </p>

      <p>
        <label><%= l('toggl.stop') %></label>
        <%= f.datetime_select :stop %>
      </p>
    <% end %>

    <%
        user_workspace = f.object.user.try(:toggl_workspace) || User.current.toggl_workspace
        if user_workspace
    %>
      <%= f.hidden_field :toggl_workspace_id, :value => user_workspace.id %>
    <% else %>
      <p>
        <label><%= l('toggl.toggl_workspace') %></label>
        <%= f.collection_select :toggl_workspace_id, TogglWorkspace.without_user.order(:name), :id, :name %>
      </p>

      <p>
        <label><%= l('toggl.toggl_project') %></label>
        <%= f.grouped_collection_select :toggl_project_id, TogglWorkspace.without_user.order(:name), :toggl_projects, :name, :id, :name, :blank => :label_none %>
      </p>

      <p>
        <label><%= l('toggl.toggl_task') %></label>
        <%= f.grouped_collection_select :toggl_task_id, TogglProject.without_user.order(:name), :toggl_tasks, :name, :id, :name, :blank => :label_none %>
      </p>
    <% end %>

    <p>
      <label><%= l('toggl.toggl_tags') %></label>
      <%= f.text_field :toggl_tags, :size => 80, :label => '' %>
    </p>

  </div>
</div>

<%= javascript_include_tag 'console_fallback', :plugin => 'redmine_toggl' %>

<% unless User.current.toggl_workspace %>
  <%= javascript_include_tag 'redmine_toggl_edit', :plugin => 'redmine_toggl' %>
<% end %>

app/views/toggl_entries/_toggl_entries.html.erb
<div class="redmine_toggl_datatables_wrapper">
  <table id="toggl_entries_table" class="serverside_datatables" width="100%" cellspacing="0" data-source="<%= data_source %>">
    <thead>
      <tr>
        <th><%= t('toggl.description') %></th>
        <th><%= t('toggl.toggl_project') %></th>
        <th class="datatable_no_order"><%= t(:field_issue) %></th>
        <th class="datatable_no_search"><%= t('toggl.duration') %></th>
        <th class="datatable_no_search"><%= t('toggl.start') %></th>
        <th class="datatable_no_order"><%= t('toggl.toggl_tags') %></th>
        <% unless for_user %>
          <th><%= l(:field_user) %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
    </tbody>
  </table>
</div>

<script language="javascript" type="text/javascript">

  var datatable_order_index = 4;
  var datatable_str = {
    search: "<%= l(:label_search) %>",
    empty_table: "<%= l(:label_no_results_found) %>",
    first: "<%= l('toggl.first') %>",
    last: "<%= l('toggl.last') %>",
    next: '>>',
    previous: '<<',
    info: "<%= l(:label_total) %>: _TOTAL_",
    yes: "<%= l(:general_text_Yes) %>",
    no: "<%= l(:general_text_No) %>",
    all: "<%= l(:label_all) %>"
  };

</script>


<%= javascript_include_tag 'console_fallback', :plugin => 'redmine_toggl' %>
<%= javascript_include_tag 'dataTables/jquery.dataTables.min', :plugin => 'redmine_toggl' %>
<%= javascript_include_tag 'dataTables/buttons/buttons.html5.min.js', :plugin => 'redmine_toggl' %>
<%= javascript_include_tag 'dataTables/buttons/buttons.print.min.js', :plugin => 'redmine_toggl' %>
<%= javascript_include_tag 'dataTables/buttons/dataTables.buttons.min.js', :plugin => 'redmine_toggl' %>
<%= javascript_include_tag 'redmine_toggl', :plugin => 'redmine_toggl' %>

<%= stylesheet_link_tag 'dataTables/jquery.dataTables.min', :plugin => 'redmine_toggl' %>
<%= stylesheet_link_tag 'dataTables/buttons/buttons.dataTables.min.css', :plugin => 'redmine_toggl' %>
<%= stylesheet_link_tag 'redmine_toggl', :plugin => 'redmine_toggl' %>

app/views/toggl_entries/all_entries.html.erb
<div class="contextual">
  <% if user_can_create_toggl_entry %>
    <%= link_to l('toggl.new_toggl_entry'), new_toggl_entry_path, :class => 'icon icon-add' %>
  <% end %>

  <%= link_to l('toggl.my_entries'), toggl_entries_path, :class => 'icon icon-user' %>
</div>

<%= title "#{t('toggl.toggl_entries')} - #{l('toggl.all_entries')}" %>

<%= render :partial => 'toggl_entries', :locals => {:data_source => all_entries_toggl_entries_path, :for_user => false} %>

app/views/toggl_entries/edit.html.erb
<%= title l('toggl.toggl_entry') %>

<%= labelled_form_for @toggl_entry, :url => toggl_entry_path(@toggl_entry) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
  <%= link_to l(:button_cancel), toggl_entries_path %>
<% end %>

app/views/toggl_entries/filter_by_user.html.erb
<div class="contextual">
  <% if user_can_create_toggl_entry %>
    <%= link_to l('toggl.new_toggl_entry'), new_toggl_entry_path, :class => 'icon icon-add' %>
  <% end %>

  <%= link_to l('toggl.my_entries'), toggl_entries_path, :class => 'icon icon-user' %>

  <% if user_can_view_others_entries %>
    <%= link_to l('toggl.all_entries'), all_entries_toggl_entries_path, :class => 'icon icon-projects' %>
  <% end %>
</div>

<h2><%= t('toggl.toggl_entries') %> - <%= link_to_user(@filter_user) %></h2>
<% html_title "#{t('toggl.toggl_entries')} - #{@filter_user.name}" %>

<%= render :partial => 'toggl_entries', :locals => {:data_source => filter_by_user_toggl_entries_path(:filter_user_id => @filter_user.id), :for_user => true} %>

app/views/toggl_entries/index.html.erb
<div class="contextual">
  <% if user_can_create_toggl_entry %>
    <%= link_to l('toggl.new_toggl_entry'), new_toggl_entry_path, :class => 'icon icon-add' %>
  <% end %>

  <% if user_can_view_others_entries %>
    <%= link_to l('toggl.all_entries'), all_entries_toggl_entries_path, :class => 'icon icon-projects' %>
  <% end %>
</div>

<%= title "#{t('toggl.toggl_entries')} - #{l('toggl.my_entries')}" %>

<%= render :partial => 'toggl_entries', :locals => {:data_source => toggl_entries_path, :for_user => true} %>

app/views/toggl_entries/new.html.erb
<%= title l('toggl.toggl_entry') %>

<%= labelled_form_for @toggl_entry, :url => toggl_entries_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
  <%= link_to l(:button_cancel), toggl_entries_path %>
<% end %>

app/views/toggl_entries/show.html.erb
<% if user_can_edit_toggl_entry(@toggl_entry) %>
  <div class="contextual">
    <%= link_to l(:button_edit), edit_toggl_entry_path(@toggl_entry), :class => 'icon icon-edit' %>
    <%= link_to l(:button_delete), @toggl_entry, :data => {:confirm => l('toggl.are_you_sure_you_want_to_delete_toggl_entry')}, :method => :delete, :class => 'icon icon-del' %>
  </div>
<% end %>

<%= title l('toggl.toggl_entry') %>

<div class="box tabular">
  <div>
    <p>
      <label><%= l(:field_user) %>: </label>
      <%= avatar(@toggl_entry.user, :size => 14) %>
      <%= link_to_user(@toggl_entry.user) %>
    </p>

    <p>
      <label><%= l(:field_issue) %>: </label>
      <%= rt_issue_link(@toggl_entry.issue) %>
    </p>

    <p>
      <label><%= l('toggl.description') %></label>
      <%= @toggl_entry.description %>
    </p>

    <p>
      <label><%= l('toggl.duration') %>: </label>
      <%= rt_format_duration(@toggl_entry.duration) %>
    </p>

    <p>
      <label><%= l('toggl.start') %>: </label>
      <%= format_time(@toggl_entry.start) %>
    </p>

    <p>
      <label><%= l('toggl.stop') %>: </label>
      <%= format_time(@toggl_entry.stop) %>
    </p>

    <p>
      <label><%= l('toggl.toggl_workspace') %>: </label>
      <%= @toggl_entry.toggl_workspace_name %>
    </p>

    <p>
      <label><%= l('toggl.toggl_project') %>: </label>
      <span style="color:<%= @toggl_entry.toggl_project_color %>">
        <%= @toggl_entry.toggl_project_name %>
      </span>
    </p>

    <p>
      <label><%= l('toggl.toggl_task') %>: </label>
      <span style="color:<%= @toggl_entry.toggl_project_color %>">
        <%= @toggl_entry.toggl_task_name %>
      </span>
    </p>

    <p>
      <label><%= l('toggl.toggl_tags') %>: </label>
      <%= @toggl_entry.clean_toggl_tags.join(',') %>
    </p>

    <% if @toggl_entry.time_entry && User.current.allowed_to?(:view_time_entries, @toggl_entry.time_entry.project) %>
      <p>
        <label><%= l('toggl.time_entry') %>: </label>
        <%= rt_time_entry_link(@toggl_entry.time_entry) %>
      </p>
    <% end %>
  </div>
</div>